version: "3.9"

networks:
  default:
services:
  spring-boot:
    build:
      context: .
    expose:
      - 8080
    networks:
      - default
    depends_on:
      - postgresql
      - mongodb
    ports:
      - 8080:8080
    environment:
      - TZ=Asia/Taipei
      - activeProfiles=docker
  postgresql:
    image: arm64v8/postgres:15-alpine
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - default
  mongodb:
    image: arm64v8/mongo:6
    container_name: mongo
    environment:
    - MONGO_ROOT_PASSWORD=root
    - MONGODB_USERNAME=mongo
    - MONGODB_PASSWORD=mongo
    - MONGODB_DATABASE=mongo
    expose:
      - 27017
    ports:
      - "27017:27017"
    networks:
      - default
  loki:
    image: grafana/loki:main-44f1d8d
    container_name: LOKI
    expose:
      - 3100
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - default
  promtail:
    image: grafana/promtail:main
    command: >
      -client.url=http://loki:3100/loki/api/v1/push
    networks:
      - default
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - default