version: "3.9"

services:
#  postgresql:
#    image: arm64v8/postgres:latest
#    environment:
#      - POSTGRES_PASSWORD=root
#    expose:
#      - 5432
#    ports:
#      - "5432:5432"
#    networks:
#      - default
#  mongodb:
#    image: arm64v8/mongo:latest
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=mongo
#      - MONGO_INITDB_ROOT_PASSWORD=mongo
#    expose:
#      - 27017
#    ports:
#      - "27017:27017"
#    networks:
#      - default
  loki:
    image: grafana/loki:main-44f1d8d
    container_name: LOKI
    expose:
      - 3100
#    volumes:
#      - ./loki/:/etc/loki/
#    command: -config.file=/etc/loki/loki.yml
    ports:
      - "3100:3100"
    networks:
      - default
  promtail:
    image: grafana/promtail:main
    expose:
      - 9090
    ports:
      - "9090:9090"
    volumes:
      - /Users/ken/Desktop/archived:/var/log
      - ./promtail.yml:/etc/promtail/promtail.yml
    command:
      - -config.file=/etc/promtail/promtail.yml
    networks:
      - default
  grafana:
    image: grafana/grafana:latest
    expose:
      - 3000
    ports:
      - "3000:3000"
    networks:
      - default

networks:
  default:
