server:
  port: 8080
# 它的主要功用是用來設置應用程式在執行時使用的配置文件（或稱為環境）
spring:
  profiles:
    active: ide
  # JDBC 資料庫連接驅動程式名稱
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    # JPA 所使用的資料庫平台
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
#  spring actuator 監控服務註解
management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /manage
logging:
  config: classpath:logback-spring.xml
  level:
    org:
      hibernate:
        # 的日誌層級設置為 DEBUG，表示輸出生成的 SQL 語句。
        SQL: DEBUG
        type:
          descriptor:
            sql:
              # 表示輸出在綁定參數時使用的相關信息，例如綁定參數的值和類型。
              BasicBinder: TRACE

springdoc:
  api-docs:
    #API 文件路徑
    path: /v3/api-docs
  swagger-ui:
    #UI 文件路徑
    path: /v3/ui-docs
    # 表示不展開文檔，默認為列表形式。
    doc-expansion: none
    # 表示按字母順序排序操作。
    operations-sorter: alpha
    # 表示按字母順序排序標籤。
    tags-sorter: alpha
    # 隱藏UI文件
#    enabled: false
########################### 自定義註解 ########################

---

spring:
  config:
    activate:
      on-profile: ide
  data:
    mongodb:
      uri: mongodb://127.0.0.1:8888/
      database: mongo
  datasource:
    url: jdbc:postgresql://localhost:5432/Test
    username: ken
    password: isabella1637

---

spring:
  config:
    activate:
      on-profile: docker
  jpa:
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      host: mongodb
      username: mongo
      password: mongo
      database: mongo
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: root

---



